import { useEffect } from 'react'
import { ExternalLink } from '../icons'

interface Product {
  title: string
  tagline: string
  url: string
  type: string
  /**
   * Cover image base path (without extension). Both `${cover}.webp` and
   * `${cover}.jpg` are expected to exist at 1600×800 (2:1) in public/images/.
   * Generated by `temp-downloads/generate-product-covers.mjs`.
   */
  cover: string
  coverAlt: string
}

const PRODUCTS: Product[] = [
  {
    title: 'Image2.fun',
    tagline: 'GPT-Image-2 提示词与生图工具站',
    url: 'https://image2.fun',
    type: '在线工具站',
    cover: '/images/product-image2',
    coverAlt: 'Image2.fun 首页截图 — 居中显示「GPT-Image-2 提示词」品牌标识',
  },
  {
    title: 'AIGC 财富自由之路',
    tagline: '小报童付费专栏',
    url: 'https://xiaobot.net/p/DuzhouMoney?refer=70e80a00-8534-4603-a6dd-69d97e47dc9c',
    type: '付费专栏',
    cover: '/images/product-aigc',
    coverAlt: 'AIGC 财富自由之路 — 小报童付费专栏封面',
  },
]

export function Products() {
  useEffect(() => {
    const previousTitle = document.title
    document.title = '产品 · 方鑫三个金'
    return () => {
      document.title = previousTitle
    }
  }, [])

  return (
    <div className="reading-column py-12 sm:py-16 md:py-20">
      <h1 className="page-title">产品</h1>
      <div className="page-divider" />
      <p className="page-intro">
        从想法、写代码、设计、上线、运营,到拉用户、收钱,全部一个人完成。
      </p>

      <ul className="list-none p-0 m-0">
        {PRODUCTS.map((p, idx) => (
          <li
            key={p.title}
            className="product-row"
            style={{
              borderTop: idx === 0 ? 'none' : '1px solid var(--color-divider)',
              paddingTop: idx === 0 ? '0' : '2.25rem',
              paddingBottom: '2.25rem',
            }}
          >
            <div className="product-row__text">
              <span
                className="block text-xs mb-2"
                style={{ color: 'var(--color-text-3)', letterSpacing: '0.1em' }}
              >
                {p.type}
              </span>
              <a
                href={p.url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-baseline gap-2 group"
              >
                <h2
                  className="m-0 font-semibold leading-tight group-hover:underline underline-offset-4 decoration-1"
                  style={{
                    color: 'var(--color-text)',
                    fontSize: 'clamp(1.25rem, 3vw, 1.6rem)',
                    textDecorationColor: 'var(--color-text-2)',
                  }}
                >
                  {p.title}
                </h2>
                <ExternalLink
                  className="w-4 h-4 opacity-50 translate-y-[-1px]"
                  style={{ color: 'var(--color-text-2)' }}
                />
              </a>
              <p
                className="m-0 mt-2 text-base"
                style={{ color: 'var(--color-text-2)' }}
              >
                {p.tagline}
              </p>
            </div>

            {/* Right-side thumbnail — small visual anchor, doesn't crowd the text. */}
            <a
              href={p.url}
              target="_blank"
              rel="noopener noreferrer"
              className="product-row__thumb"
              aria-label={`访问 ${p.title}`}
              tabIndex={-1} /* primary link is the title; this is decorative */
            >
              <picture>
                <source srcSet={`${p.cover}.webp`} type="image/webp" />
                <img
                  src={`${p.cover}.jpg`}
                  alt={p.coverAlt}
                  width={1600}
                  height={800}
                  loading={idx === 0 ? 'eager' : 'lazy'}
                  decoding="async"
                />
              </picture>
            </a>
          </li>
        ))}
      </ul>

      <style>{`
        .product-row {
          display: flex;
          gap: 1.5rem;
          align-items: flex-start;
        }
        .product-row__text {
          flex: 1 1 auto;
          min-width: 0;
        }
        .product-row__thumb {
          flex: 0 0 auto;
          width: 200px;
          display: block;
          line-height: 0;
          overflow: hidden;
          border-radius: 2px;
          background: var(--color-divider);
          margin-top: 0.25rem; /* line up with the type label */
        }
        .product-row__thumb img {
          display: block;
          width: 100%;
          height: auto;
          aspect-ratio: 2 / 1;
          object-fit: cover;
          transition: opacity 200ms ease;
        }
        .product-row__thumb:hover img,
        .product-row__thumb:focus-visible img {
          opacity: 0.9;
        }

        @media (max-width: 640px) {
          .product-row {
            gap: 1rem;
          }
          .product-row__thumb {
            width: 110px;
          }
        }
      `}</style>
    </div>
  )
}
